/**
 * Turns a saved Agent SDK session into what the app shows for a past
 * conversation: a title for the menu bar's "Past" menu, and the question and
 * answer pairs that refill the transcript card when it is reopened. Pure; the
 * SDK reads live in pastConversations.ts.
 *
 * A Clicky user turn is stored as each screenshot followed by its label text,
 * then the transcript as the last text block (agentSession.ts builds it). A
 * spoken slash command is a plain string. Tool results come back as user
 * messages too, and are not questions.
 */

export interface ConversationExchange {
  question: string;
  answer: string;
}

/** The fields of the SDK's SessionMessage this module reads. */
export interface StoredSessionMessage {
  type: string;
  parent_tool_use_id: string | null;
  message: unknown;
}

/** The fields of the SDK's SDKSessionInfo this module reads. */
export interface StoredSessionTitles {
  customTitle?: string | undefined;
  summary: string;
}

const UNTITLED_CONVERSATION_TITLE = "untitled conversation";
const MAXIMUM_TITLE_LENGTH = 80;

/** Markers the CLI writes as user text that the user never said. */
const SYNTHETIC_USER_TEXT_PREFIXES = ["[Request interrupted"];

/** The transcript of a Clicky user turn, or null for tool results and synthetic notices. */
export function questionTextFromUserMessage(storedMessage: unknown): string | null {
  const content = contentOf(storedMessage);
  if (typeof content === "string") {
    return usableQuestionText(content);
  }
  if (!Array.isArray(content)) return null;
  if (content.some((block) => blockTypeOf(block) === "tool_result")) return null;

  const textBlocks = content.filter((block) => blockTypeOf(block) === "text");
  const lastTextBlock = textBlocks.at(-1) as { text?: unknown } | undefined;
  return typeof lastTextBlock?.text === "string" ? usableQuestionText(lastTextBlock.text) : null;
}

/** Every text block of an assistant message joined; thinking and tool calls are left out. */
export function answerTextFromAssistantMessage(storedMessage: unknown): string {
  const content = contentOf(storedMessage);
  if (typeof content === "string") return content.trim();
  if (!Array.isArray(content)) return "";
  return content
    .filter((block) => blockTypeOf(block) === "text")
    .map((block) => (typeof (block as { text?: unknown }).text === "string" ? (block as { text: string }).text.trim() : ""))
    .filter((text) => text !== "")
    .join(" ");
}

/**
 * Pairs each question with everything Claude said until the next question,
 * oldest first, keeping the most recent `maximumExchangeCount`. Subagent
 * messages (a parent tool use) belong to a tool call, not the conversation.
 */
export function conversationExchangesFromSessionMessages(
  storedMessages: readonly StoredSessionMessage[],
  maximumExchangeCount: number
): ConversationExchange[] {
  const exchanges: ConversationExchange[] = [];
  let exchangeInProgress: ConversationExchange | null = null;

  for (const storedMessage of storedMessages) {
    if (storedMessage.parent_tool_use_id !== null) continue;

    if (storedMessage.type === "user") {
      const questionText = questionTextFromUserMessage(storedMessage.message);
      if (questionText === null) continue;
      exchangeInProgress = { question: questionText, answer: "" };
      exchanges.push(exchangeInProgress);
    } else if (storedMessage.type === "assistant" && exchangeInProgress !== null) {
      const answerText = answerTextFromAssistantMessage(storedMessage.message);
      if (answerText === "") continue;
      exchangeInProgress.answer = exchangeInProgress.answer === "" ? answerText : `${exchangeInProgress.answer} ${answerText}`;
    }
  }

  return maximumExchangeCount > 0 ? exchanges.slice(-maximumExchangeCount) : [];
}

/**
 * The menu title: a title set with /rename or generated by Claude Code, else
 * the first question. The SDK's own fallback is the first user text, which
 * for Clicky is a screenshot label, so that is never used as a title.
 */
export function titleForPastConversation(
  storedSessionTitles: StoredSessionTitles,
  firstQuestionText: string | null
): string {
  const candidateTitles = [storedSessionTitles.customTitle, storedSessionTitles.summary, firstQuestionText];
  for (const candidateTitle of candidateTitles) {
    const trimmedTitle = candidateTitle?.replace(/\s+/g, " ").trim();
    if (trimmedTitle && !looksLikeScreenshotLabel(trimmedTitle)) {
      return shortenedTitle(trimmedTitle);
    }
  }
  return UNTITLED_CONVERSATION_TITLE;
}

/** Matches the label agentSession.ts writes after each screenshot. */
export function looksLikeScreenshotLabel(text: string): boolean {
  return /\(image dimensions: \d+x\d+ pixels, screen index \d+\)/.test(text);
}

function usableQuestionText(rawText: string): string | null {
  const trimmedText = rawText.trim();
  if (trimmedText === "" || looksLikeScreenshotLabel(trimmedText)) return null;
  if (SYNTHETIC_USER_TEXT_PREFIXES.some((prefix) => trimmedText.startsWith(prefix))) return null;
  return trimmedText;
}

function shortenedTitle(title: string): string {
  return title.length <= MAXIMUM_TITLE_LENGTH ? title : `${title.slice(0, MAXIMUM_TITLE_LENGTH - 1).trimEnd()}…`;
}

function contentOf(storedMessage: unknown): unknown {
  if (typeof storedMessage !== "object" || storedMessage === null) return undefined;
  return (storedMessage as { content?: unknown }).content;
}

function blockTypeOf(block: unknown): unknown {
  return typeof block === "object" && block !== null ? (block as { type?: unknown }).type : undefined;
}
